microblog/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    url(r'^$', include('web.urls', namespace='web')),
    url(r'^u/', include('usuarios.urls', namespace="usuarios")),
    url(r'^p/', include('posts.urls', namespace="posts")),
    url(r'^admin/', include(admin.site.urls)),
)

posts/urls.py
from django.conf.urls import patterns, url
from . import views


urlpatterns = (
	url(r'^savepost', views.guardar_post, name="savepost"),
	)

usuarios/urls.py
from django.conf.urls import patterns, url
from . import views
from views import Registro_User


urlpatterns = (
	url(r'^login', views.login_u, name="login"),
	url(r'^logout', views.logout_u, name="logout"),
	#url(r'^registro', views.registro_u, name="registro"),
	url(r'^registro$', Registro_User.as_view(), name="registro"),
	)

web/urls.py
from django.conf.urls import patterns, url
from . import views


urlpatterns = (
	url(r'^$', views.index, name="index"),
	url(r'^success$', views.success, name="success"),
	)

posts/models.py
from django.db import models
from django.contrib.auth.models import User

class Post(models.Model):

	usuario = models.ForeignKey(User)
	fecha = models.DateTimeField(auto_now_add=True)
	contenido = models.CharField(max_length=130)

	def __unicode__(self):
		return u'%s ' % (self.usuario)

posts/forms.py
from django.forms import ModelForm
from .models import Post

class PostForm(ModelForm):


    class Meta:
        model = Post
        exclude = ('usuario',) # excluyo de la forma el campo 'usuario', solo recibo el texto de la publicacion

usuarios/forms.py
from django.forms import ModelForm
from django import forms
from django.contrib.auth.models import User

class UserForm(ModelForm):
	password = forms.CharField(label='Password', widget=forms.PasswordInput(attrs={'placeholder': 'contrasena'}))


	class Meta:
		model = User
		fields = ['username', 'first_name', 'last_name', 'email', 'password']



	def save(self, commit=True):
    	# Save the provided password in hashed format
		user = super(forms.ModelForm, self).save(commit=False)
		user.set_password(self.cleaned_data["password"])
		if commit:
			user.save()
		return user

posts/views.py
from django.shortcuts import render_to_response
from django.template import RequestContext
from django.http import HttpResponse, HttpResponseRedirect
from django.core.urlresolvers import reverse
from .models import *


from posts.forms import PostForm
def guardar_post(request):

	if request.POST:

		form = PostForm(request.POST)

		if form.is_valid:

			post = form.save(commit = False) #todavia no guardes la publicacion! me falta un dato . .
			post.usuario = request.user # le damos a la publicacion el id del usuario actual (FK)
			post.save() # ahora si guardo la publicacion

			return HttpResponseRedirect(reverse('web:index'))
	else:
		return HttpResponseRedirect(reverse('web:index'))

usuarios/views.py
from django.template import RequestContext
from django.http import HttpResponse, HttpResponseRedirect
#sfrom django.core.context_processors import csrfs_token
from django.core.urlresolvers import reverse
from django.contrib.auth.models import User




from usuarios.forms import UserForm
from django.views.generic.edit import CreateView
from django.core.urlresolvers import reverse_lazy
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin

class Registro_User(SuccessMessageMixin, CreateView):
    form_class = UserForm
    template_name = 'Nosuccess.html'
    success_url = reverse_lazy('web:index')
    #success_url = reverse('web:success')

"""
    def dispatch(self, request, *args, **kwargs):
        print args
        print kwargs
        #kwargs = {""}
        print request.user
        messages.success(request,"usuario creado")
        messages.add_message(request, messages.INFO, 'Hello world.')

        return super(Registro_User, self).dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        print "valid"
        messages.info(
            self.request,
            "Tienes un mensaje"
            )
        return super(Registro_User, self).form_valid(form)
"""       

"""
from django.shortcuts import render

def registro_u(request):
    if request.POST:
        form = UserForm(request.POST)
        if form.is_valid:
            form.save()
            return HttpResponseRedirect(reverse('web:index'))
        else:
            return render(request, "Nosuccess.html", context_instance=RequestContext(request))
    else:
        return HttpResponseRedirect(reverse('web:index'))
"""


from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import authenticate, login, logout
def login_u(request):
    
    if  request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
    
        if form.is_valid():
    
            usuario = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(username=usuario, password=password)
    
            if user is not None and user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('web:index'))
    
            else:
                return HttpResponse('Algo salio mal, el usuario no existe o no esta activo')
        else:
            return HttpResponse('El formulario no es valido')
    else:
        return HttpResponseRedirect(reverse('web:index'))


from django.contrib.auth.decorators import login_required
#@login_required(login_url='/user/login/')
def logout_u(request):
    logout(request)
    return HttpResponseRedirect(reverse('web:index'))

web/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.template import RequestContext

from django.contrib.auth.forms import AuthenticationForm
from django.core.context_processors import csrf

from usuarios.forms import UserForm
from posts.models import *

def index(request):
	auth_form = AuthenticationForm()
	reg_form = UserForm()
	posts = Post.objects.all()
	argumentos = {'title': 'Inicio', 'auth_form': auth_form, 'reg_form': reg_form, 'posts': posts }
	return render(request, "base.html", argumentos, context_instance=RequestContext(request))


def success(request):
	#return HttpResponse("El usuario se ha creado")
	return render(request, "base.html", context_instance=RequestContext(request))

web/templates/Nosuccess.html
{% block contenido %}
<h1> No se pudo crear el usuario</h1>
{% endblock%} 

web/templates/base.html
<!DOCTYPE html>

<html class="no-js" lang="es">

<head>

	<meta charset="utf-8">

	<meta name="viewport" content="width=device-width, initial-scale=1.0">

	<title>Blog | {{title}}</title>

	<link rel="stylesheet" href="{{STATIC_URL}}skeleton.css">

	<link rel="stylesheet" href="{{STATIC_URL}}base.css">

</head>

<body>
{{ messages }}

	{% if not user.is_authenticated %}


		<div class="container">

				<div class="eight columns">

					<h2>MicroBlog</h2>


						<h4>Login</h4>

						<form action="{% url 'usuarios:login' %}" method="POST">{%csrf_token%}
								<ul>


								{{ auth_form.as_ul }}

								<input class="button" type="submit" name="" value="Ingresar" placeholder="">

							</ul>
						</form>

				</div>

				<div class="four columns">

					<h4>Registro</h4>

					<form action="{% url 'usuarios:registro' %}" method="post" accept-charset="utf-8"> {% csrf_token %}
							<ul>


							{{reg_form.as_p}}

							<input class="button" type="submit" name="" value="Registrar" placeholder="">
							</ul>
					</form>

				</div>

		</div>

	{% else %}

		<div class="container">

    		<div class="seven columns">

						<h3>MicroBlog</h3>

						<ul>

								<li>

									<h6>Publicar Algo</h6>

										<form action="{% url 'posts:savepost' %}" method="post" accept-charset="utf-8">{% csrf_token %}

												<input name="contenido" type="text" class="form-control status-box" placeholder="Que pasa por tu mente?" >

												<input class="button radius right tiny tuit" type="submit" name="" value="Publicar" placeholder="">

										</form>

								</li>


								<li> 	<a href=""> </i>Inicio	</a>	</li>

								<li>	<a href="#"><strong>{{user.first_name}} {{user.last_name}} ({{user.username}})</strong></a></li>

								<li>	<a href="{% url 'usuarios:logout' %}" title="logout">Cerrar Sesion</a></li>

								<li>	Universidad del Valle - Sede Tulua </li>

								<li>	Ingeniux</li>

								<li>	<a href="https://github.com/Ingeniux/taller-django">	<img src="{{STATIC_URL}}GitHub-Mark-32px.png"/> </a>	</li>

						</ul>

        </div>

				<div class="six columns">

								<ul>
									{% for item in posts%}
									<li>
										{{item.contenido}}
										<br>
										<small>{{item.usuario}} - {{item.fecha}}</small>	
									</li>
									{%endfor%}
								</ul>


    			</div>
				</div>



		{% endif %}

	{%block contenido%}{%endblock%}

</body>
</html>